# Generated by Django 2.1.13 on 2019-10-11 19:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reset_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='body',
            field=wagtail.core.fields.StreamField([('titre', wagtail.core.blocks.StructBlock([('niveau', wagtail.core.blocks.ChoiceBlock(choices=[('h2', 'Titre de niveau 2'), ('h3', 'Titre de niveau 3'), ('h4', 'Titre de niveau 4'), ('h5', 'Titre de niveau 5'), ('h6', 'Titre de niveau 6')], icon='title')), ('texte', wagtail.core.blocks.TextBlock(icon='pilcrow'))])), ('paragraphe', wagtail.core.blocks.StructBlock([('texte', wagtail.core.blocks.RichTextBlock(icon='pilcrow'))])), ('bouton', wagtail.core.blocks.StructBlock([('outline', wagtail.core.blocks.BooleanBlock(default=False, label='Bordures colorées uniquement', required=False)), ('texte', wagtail.core.blocks.TextBlock(icon='pilcrow')), ('lien', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(page_type=['base.SitePage'])), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('lien_externe', wagtail.core.blocks.URLBlock(help_text='Lien vers un site externe.', icon='link')), ('ancre', wagtail.core.blocks.TextBlock(help_text='Ancre dans la page. Ex : #infos', icon='fa fa-anchor'))], help_text='Lien associé au bouton ; optionnel', icon='link', max_num=1, required=False))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('legende', wagtail.core.blocks.RichTextBlock(features=['ol', 'ul', 'bold', 'italic', 'link', 'document-link'], icon='pilcrow', label='légende', required=False)), ('lien', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(page_type=['base.SitePage'])), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('lien_externe', wagtail.core.blocks.URLBlock(help_text='Lien vers un site externe.', icon='link')), ('ancre', wagtail.core.blocks.TextBlock(help_text='Ancre dans la page. Ex : #infos', icon='fa fa-anchor'))], help_text="Lien associé à l'image ; optionnel", icon='link', max_num=1, required=False))])), ('embarque', wagtail.core.blocks.StructBlock([('media', wagtail.embeds.blocks.EmbedBlock(help_text='Lien vers le média embarqué.', icon='link'))]))], blank=True, null=True, verbose_name='contenu'),
        ),
    ]
