# Generated by Django 2.2.10 on 2020-02-21 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('base', '0005_pouvoir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.TextField()),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='submit time')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page')),
                ('pouvoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Pouvoir')),
            ],
            options={
                'verbose_name': 'form submission',
                'abstract': False,
            },
        ),
    ]
