# Generated by Django 2.2.10 on 2020-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrutin',
            name='ouvert',
            field=models.BooleanField(blank=True, default=False, help_text="Tant que le scrutin n'est pas ouvert, il est fonctionnel pour les tests mais les votes ne sont pas enregistrés.", verbose_name='Scrutin ouvert'),
        ),
    ]
