# Generated by Django 2.2.10 on 2020-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_scrutin_ouvert'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouvoir',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact alternatif en cas de courriel en erreur'),
        ),
        migrations.AddField(
            model_name='pouvoir',
            name='ponderation',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Pondération'),
        ),
    ]
