# Generated by Django 2.2.12 on 2020-04-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pouvoirs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouvoir',
            name='collectif',
            field=models.CharField(blank=True, help_text='Le pouvoir doit au moins désigner un nom, un prénom ou un nom de collectif.', max_length=100, null=True, verbose_name='Mandaire du collectif'),
        ),
        migrations.AlterField(
            model_name='pouvoir',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pouvoir',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
    ]
