# Generated by Django 2.2.12 on 2020-05-10 16:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_pouvoir_collectif'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sujet', models.CharField(max_length=255)),
                ('texte', models.TextField(verbose_name='Email, version texte')),
                ('html', wagtail.core.fields.RichTextField(blank=True, verbose_name='Email, version HTML')),
                ('scrutin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Scrutin')),
            ],
            options={
                'verbose_name': 'Modèle de courriel',
                'verbose_name_plural': 'Modèles de courriels',
            },
        ),
    ]
