# Generated by Django 2.2.12 on 2020-06-02 09:19

from django.db import migrations, models
import gvot.base.validators
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_scrutin_confirm_tpl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Peut inclure du balisage de gabarit Django. Voir la documentation.', validators=[gvot.base.validators.validate_template], verbose_name='contenu du courriel, version HTML'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='sujet',
            field=models.CharField(help_text='Le sujet du courriel. Peut inclure du balisage de gabarit Django. Voir la documentation.', max_length=255, validators=[gvot.base.validators.validate_template], verbose_name='sujet du courriel'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='texte',
            field=models.TextField(help_text='Peut inclure du balisage de gabarit Django. Voir la documentation.', validators=[gvot.base.validators.validate_template], verbose_name='contenu du courriel, version texte'),
        ),
    ]
