# Generated by Django 2.2.18 on 2021-02-09 15:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_formfield_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampPersonnalise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(help_text='Exemples : téléphone, surnom...', max_length=50)),
                ('contenu', models.CharField(max_length=255)),
                ('pouvoir', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='champ_perso', to='base.Pouvoir')),
            ],
        ),
    ]
