# Generated by Django 2.2.19 on 2021-03-04 15:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_champpersonnalise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courriel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courriel', models.EmailField(max_length=254)),
                ('pouvoir', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriels', to='base.Pouvoir')),
            ],
        ),
    ]
